package:
  name: spotlight
  version: "0.1.0"

source:
  git_rev: v0.1.0
  git_url: https://github.com/maciejkula/spotlight.git

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - numpy
    - scipy
    - h5py
    - pytorch 0.1.12

test:
  imports:
    - spotlight

about:
  home: https://github.com/maciejkula/spotlight
  license: MIT
  license_file: LICENSE